### ISSUE TITLE
Install npm packages with npm install  with error

### ISSUE THREAD

**Issue by wuming123057** [bigardone/phoenix-trello#5]
I delete the import_config "dev.secret.exs" in dev.exs files.
And I install npm packages with npm install  with error
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by wuming123057** [comment]
This is my npm errors!
