### ISSUE TITLE
Unable to run mix ecto.migrate

### ISSUE THREAD

**Issue by ltenzil** [bigardone/phoenix-trello#58]
Followed quite few forums, couldn't figure it out as i am a newbie, Please help me out.
Thanks in advance
**Error:**
** (exit) exited in: :gen_server.call(#PID<0.225.0>, {:checkout, #Reference<0.2683396477.2851078145.127520>, true, :infinity}, 5000)
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function true.find/2 is undefined (module true is not available)
            true.find(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "boolin", oid: 16, output: "boolout", receive: "boolrecv", send: "boolsend", type: "bool"}, :any)
            (postgrex) lib/postgrex/types.ex:138: Postgrex.Types.find/4
            (postgrex) lib/postgrex/types.ex:131: anonymous fn/4 in Postgrex.Types.associate_type_infos/2
            (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
            (postgrex) lib/postgrex/types.ex:130: Postgrex.Types.associate_type_infos/2
            (postgrex) lib/postgrex/type_server.ex:122: Postgrex.TypeServer.associate/2
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by ghost** [comment]
Ditto, had the same problem. Did you find a solution?
