### ISSUE TITLE
Webpack Compilation Error

### ISSUE THREAD

**Issue by johnmcdowall** [bigardone/phoenix-trello#9]
Cloned the repo, followed the instructions. Webpack throws a compilation error which seems very strange: 

```
20:48 [~/.../phoenix-trello master] mix phoenix.server
==> base64url (compile)
Compiled src/base64url.erl
==> connection
Compiled lib/connection.ex
Generated connection app
==> fs (compile)
Compiled src/sys/inotifywait_win32.erl
Compiled src/sys/fsevents.erl
Compiled src/sys/inotifywait.erl
Compiled src/fs_event_bridge.erl
Compiled src/fs_sup.erl
Compiled src/fs_app.erl
Compiled src/fs_server.erl
Compiled src/fs.erl
==> bunt
Compiled lib/bunt.ex
Compiled lib/bunt_ansi.ex
Generated bunt app
==> jose
Compiled src/jose_jwa.erl
Compiled src/jose_jwk_oct.erl
Compiled src/jose_jwe.erl
Compiled src/jose_jwa_concat_kdf.erl
Compiled src/jose_jwe_alg.erl
Compiled src/jose_jwe_alg_dir.erl
Compiled src/jose_jws_alg.erl
Compiled src/jose_jwk.erl
Compiled src/jose_sup.erl
Compiled src/jose_jwe_alg_rsa.erl
Compiled src/jose_jwe_alg_ecdh_es.erl
Compiled src/jose.erl
Compiled src/jose_jwe_alg_aes_kw.erl
Compiled src/jose_jwk_kty.erl
Compiled src/jose_jwk_kty_ec.erl
Compiled src/jose_jwk_kty_rsa.erl
Compiled src/jose_jwk_pem.erl
Compiled src/jose_app.erl
Compiled src/jose_jwe_zip.erl
Compiled src/jose_jwa_pkcs1.erl
Compiled src/jose_jwe_alg_pbes2.erl
Compiled src/jose_block_encryptor.erl
Compiled src/jose_jwe_enc.erl
Compiled src/jose_jwe_enc_aes.erl
Compiled src/jose_jwa_aes.erl
Compiled src/jose_jwk_set.erl
Compiled src/jose_jwa_pkcs5.erl
Compiled src/jose_jwa_pkcs7.erl
Compiled src/jose_server.erl
Compiled src/jose_jws.erl
Compiled src/jose_jws_alg_ecdsa.erl
Compiled src/jose_jws_alg_hmac.erl
Compiled src/jose_jws_alg_none.erl
Compiled src/jose_jws_alg_rsa_pkcs1_v1_5.erl
Compiled src/jose_jws_alg_rsa_pss.erl
Compiled src/jose_jwk_kty_oct.erl
Compiled src/jose_jwa_unsupported.erl
Compiled src/jose_jwt.erl
Compiled src/jose_jwa_aes_kw.erl
Compiled src/jose_json.erl
Compiled src/jose_json_jiffy.erl
Compiled src/jose_json_jsone.erl
Compiled src/jose_json_jsx.erl
Compiled src/jose_json_poison.erl
Compiled src/jose_json_poison_compat_encoder.erl
Compiled src/jose_json_poison_ord_encoder.erl
Compiled src/jose_json_unsupported.erl
Compiled lib/jose/poison.ex
Compiled lib/jose.ex
Compiled lib/jose/jwa.ex
Compiled lib/jose/jwe.ex
Compiled lib/jose/jwt.ex
Compiled lib/jose/jws.ex
Compiled lib/jose/jwk.ex
Compiled lib/jose/poison/ord_encoder.ex
Generated jose app
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_app.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch.erl
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> poison
Compiled lib/poison.ex
Compiled lib/poison/parser.ex
Compiled lib/poison/decoder.ex
Compiled lib/poison/encoder.ex
Generated poison app
cc -g -O3 -Wall -I/usr/local/Cellar/erlang/18.2.1/lib/erlang/erts-7.2.1/include -Ic_src -fPIC -shared -dynamiclib -undefined dynamic_lookup -o priv/bcrypt_nif.so c_src/bcrypt_nif.c c_src/blowfish.c
==> comeonin
Compiled lib/comeonin/tools.ex
Compiled lib/comeonin/pbkdf2/base64.ex
Compiled lib/comeonin/config.ex
Compiled lib/comeonin/bcrypt/base64.ex
Compiled lib/comeonin.ex
Compiled lib/comeonin/pbkdf2.ex
Compiled lib/comeonin/bcrypt.ex
Generated comeonin app
==> ex_machina
Compiled lib/ex_machina/sequence.ex
Compiled lib/ex_machina/ecto.ex
Compiled lib/ex_machina.ex
Generated ex_machina app
==> credo
Compiled lib/credo/check/code_pattern.ex
Compiled lib/credo.ex
Compiled lib/credo/check.ex
Compiled lib/credo/check/params.ex
Compiled lib/credo/check/property_value.ex
Compiled lib/credo/check/refactor/helper.ex
Compiled lib/credo/cli/command.ex
Compiled lib/credo/cli/command/categories.ex
lib/credo/cli/command/help.ex:47: warning: an expression is always required on the right side of ->. Please provide a value after ->
Compiled lib/credo/cli/command/version.ex
Compiled lib/credo/cli/filename.ex
Compiled lib/credo/cli/command/help.ex
Compiled lib/credo/cli/output/categories.ex
Compiled lib/credo/cli/sorter.ex
Compiled lib/credo/cli/output.ex
Compiled lib/credo/code/name.ex
Compiled lib/credo/cli/output/ui.ex
Compiled lib/credo/code/parameters.ex
Compiled lib/credo/code/module.ex
Compiled lib/credo/code/block.ex
Compiled lib/credo/issue.ex
Compiled lib/credo/code/scope.ex
Compiled lib/credo/code/strings.ex
Compiled lib/credo/exs_loader.ex
Compiled lib/credo/check/warning/operation_with_constant_result.ex
Compiled lib/credo/check/warning/name_redeclaration_by_case.ex
Compiled lib/credo/check/warning/name_redeclaration_by_def.ex
Compiled lib/credo/check/warning/operation_on_same_values.ex
Compiled lib/credo/check/warning/name_redeclaration_by_fn.ex
Compiled lib/credo/cli/output/issues_grouped_by_category.ex
Compiled lib/credo/cli/output/issue_helper.ex
Compiled lib/credo/cli/command/suggest.ex
Compiled lib/credo/cli/command/list.ex
Compiled lib/credo/cli/command/explain.ex
Compiled lib/credo/config.ex
Compiled lib/credo/cli.ex
Compiled lib/credo/check/refactor/unless_with_else.ex
Compiled lib/credo/check/warning/name_redeclaration_by_assignment.ex
Compiled lib/credo/cli/output/summary.ex
Compiled lib/credo/check/refactor/negated_conditions_with_else.ex
Compiled lib/credo/check/refactor/negated_conditions_in_unless.ex
Compiled lib/credo/check/readability/variable_names.ex
Compiled lib/credo/check/readability/module_names.ex
Compiled lib/credo/check/readability/module_attribute_names.ex
Compiled lib/credo/check/consistency/tabs_or_spaces.ex
Compiled lib/credo/check/consistency/line_endings.ex
Compiled lib/credo/check/design/tag_helper.ex
Compiled lib/credo/severity.ex
Compiled lib/mix/tasks/credo.ex
Compiled lib/credo/source_file.ex
Compiled lib/credo/service/source_file_scopes.ex
Compiled lib/credo/code/sigils.ex
Compiled lib/credo/service/source_file_without_strings_and_sigils.ex
Compiled lib/credo/service/source_file_code_only.ex
Compiled lib/credo/sources.ex
Compiled lib/credo/check/design/tag_fixme.ex
Compiled lib/credo/check/design/tag_todo.ex
Compiled lib/credo/check/readability/function_names.ex
Compiled lib/credo/check/readability/max_line_length.ex
Compiled lib/credo/check/readability/module_doc.ex
Compiled lib/credo/check/consistency/exception_names.ex
Compiled lib/credo/check/design/alias_usage.ex
Compiled lib/credo/check/readability/trailing_blank_line.ex
Compiled lib/credo/check/readability/trailing_white_space.ex
Compiled lib/credo/check/design/duplicated_code.ex
Compiled lib/credo/check/refactor/cond_statements.ex
Compiled lib/credo/check/readability/predicate_function_names.ex
Compiled lib/credo/check/refactor/case_trivial_matches.ex
Compiled lib/credo/check/refactor/pipe_chain_start.ex
Compiled lib/credo/check/refactor/match_in_condition.ex
Compiled lib/credo/check/warning/iex_pry.ex
Compiled lib/credo/check/warning/io_inspect.ex
Compiled lib/credo/check/warning/unused_tuple_operation.ex
Compiled lib/credo/check/refactor/function_arity.ex
Compiled lib/credo/check/warning/unused_list_operation.ex
Compiled lib/credo/check/warning/unused_enum_operation.ex
Compiled lib/credo/check/warning/unused_string_operation.ex
Compiled lib/credo/check/refactor/cyclomatic_complexity.ex
Compiled lib/credo/priority.ex
Compiled lib/credo/check/warning/unused_keyword_operation.ex
Compiled lib/credo/check/refactor/nesting.ex
Compiled lib/credo/check/refactor/abc_size.ex
Compiled lib/credo/cli/filter.ex
Compiled lib/credo/check/refactor/perceived_complexity.ex
Compiled lib/credo/issue_meta.ex
Compiled lib/credo/code.ex
Compiled lib/credo/cli/output/issues_short_list.ex
Compiled lib/credo/check/consistency/tabs_or_spaces/spaces.ex
Compiled lib/credo/check/runner.ex
Compiled lib/credo/check/consistency/helper.ex
Compiled lib/credo/check/consistency/tabs_or_spaces/tabs.ex
Compiled lib/credo/check/code_helper.ex
Compiled lib/credo/check/consistency/line_endings/windows.ex
Compiled lib/credo/check/consistency/line_endings/unix.ex
Compiled lib/credo/check/consistency/exception_names/prefix_and_suffix_collector.ex
Compiled lib/credo/cli/output/issues_by_scope.ex
Compiled lib/credo/cli/output/explain.ex
Compiled lib/credo/check/warning/unused_function_return_helper.ex
Generated credo app
==> cowlib (compile)
Compiled src/cow_spdy.erl
Compiled src/cow_qs.erl
Compiled src/cow_multipart.erl
Compiled src/cow_http_te.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_date.erl
Compiled src/cow_http.erl
Compiled src/cow_cookie.erl
Compiled src/cow_mimetypes.erl
==> cowboy (compile)
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_websocket.erl
Compiled src/cowboy_protocol.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy.erl
Compiled src/cowboy_req.erl
Compiled src/cowboy_http.erl
==> uuid
Compiled lib/uuid.ex
Generated uuid app
==> plug
Compiled lib/plug.ex
Compiled lib/plug/conn/status.ex
Compiled lib/plug/builder.ex
Compiled lib/plug/conn/unfetched.ex
Compiled lib/plug/adapters/cowboy.ex
Compiled lib/plug/conn/adapter.ex
Compiled lib/plug/conn/query.ex
Compiled lib/plug/conn/cookies.ex
Compiled lib/plug/crypto.ex
Compiled lib/plug/conn/wrapper_error.ex
Compiled lib/plug/crypto/key_generator.ex
Compiled lib/plug/crypto/message_verifier.ex
Compiled lib/plug/crypto/message_encryptor.ex
Compiled lib/plug/html.ex
Compiled lib/plug/error_handler.ex
Compiled lib/plug/logger.ex
Compiled lib/plug/conn/utils.ex
Compiled lib/plug/request_id.ex
Compiled lib/plug/session.ex
Compiled lib/plug/router.ex
Compiled lib/plug/exceptions.ex
Compiled lib/plug/supervisor.ex
Compiled lib/plug/session/store.ex
Compiled lib/plug/session/ets.ex
Compiled lib/plug/session/cookie.ex
Compiled lib/plug/head.ex
Compiled lib/plug/upload.ex
Compiled lib/plug/method_override.ex
Compiled lib/plug/router/utils.ex
Compiled lib/plug/test.ex
Compiled lib/plug/adapters/translator.ex
Compiled lib/plug/parsers.ex
Compiled lib/plug/adapters/test/conn.ex
Compiled lib/plug/adapters/cowboy/handler.ex
Compiled lib/plug/parsers/urlencoded.ex
Compiled lib/plug/parsers/multipart.ex
Compiled lib/plug/adapters/cowboy/conn.ex
Compiled lib/plug/parsers/json.ex
Compiled lib/plug/ssl.ex
Compiled lib/plug/conn.ex
Compiled lib/plug/static.ex
Compiled lib/plug/csrf_protection.ex
Compiled lib/plug/debugger.ex
Compiled lib/plug/mime.ex
Generated plug app
==> guardian
Compiled lib/guardian/phoenix/controller.ex
Compiled lib/guardian/claim_valiation.ex
Compiled lib/guardian/channel.ex
Compiled lib/guardian/keys.ex
Compiled lib/guardian/hooks.ex
Compiled lib/guardian/plug/error_handler.ex
Compiled lib/guardian/plug/ensure_authenticated.ex
Compiled lib/guardian/plug/ensure_permissions.ex
Compiled lib/guardian/plug/load_resource.ex
Compiled lib/guardian/utils.ex
Compiled lib/guardian/plug/verify_session.ex
Compiled lib/guardian/jwt.ex
Compiled lib/guardian/serializer.ex
Compiled lib/guardian/plug/verify_header.ex
Compiled lib/guardian/claims.ex
Compiled lib/guardian/plug.ex
Compiled lib/guardian.ex
Compiled lib/guardian/permissions.ex
Generated guardian app
==> phoenix_html
Compiled lib/phoenix_html/format.ex
Compiled lib/phoenix_html.ex
Compiled lib/phoenix_html/engine.ex
Compiled lib/phoenix_html/tag.ex
Compiled lib/phoenix_html/link.ex
Compiled lib/phoenix_html/safe.ex
Compiled lib/phoenix_html/form_data.ex
Compiled lib/phoenix_html/form.ex
Generated phoenix_html app
==> phoenix
Compiled lib/mix/tasks/phoenix.gen.secret.ex
Compiled lib/mix/tasks/phoenix.digest.ex
Compiled lib/mix/tasks/compile.phoenix.ex
Compiled lib/mix/tasks/phoenix.gen.channel.ex
Compiled lib/mix/tasks/phoenix.gen.json.ex
Compiled lib/mix/tasks/phoenix.routes.ex
Compiled lib/mix/tasks/phoenix.server.ex
Compiled lib/phoenix.ex
Compiled lib/mix/phoenix.ex
Compiled lib/mix/tasks/phoenix.gen.html.ex
Compiled lib/phoenix/code_reloader/proxy.ex
Compiled lib/phoenix/code_reloader.ex
Compiled lib/mix/tasks/phoenix.gen.model.ex
Compiled lib/phoenix/code_reloader/server.ex
Compiled lib/phoenix/controller/pipeline.ex
Compiled lib/phoenix/config.ex
Compiled lib/phoenix/endpoint/handler.ex
Compiled lib/phoenix/digester.ex
Compiled lib/phoenix/endpoint/cowboy_handler.ex
Compiled lib/phoenix/endpoint/server.ex
Compiled lib/phoenix/endpoint/cowboy_websocket.ex
Compiled lib/phoenix/endpoint/watcher.ex
Compiled lib/phoenix/endpoint.ex
Compiled lib/phoenix/endpoint/adapter.ex
Compiled lib/phoenix/endpoint/instrument.ex
Compiled lib/phoenix/exceptions.ex
Compiled lib/phoenix/pubsub/gc.ex
Compiled lib/phoenix/pubsub/local_supervisor.ex
Compiled lib/phoenix/naming.ex
Compiled lib/phoenix/pubsub/pg2.ex
Compiled lib/phoenix/pubsub.ex
Compiled lib/phoenix/pubsub/pg2_server.ex
Compiled lib/phoenix/router/resource.ex
Compiled lib/phoenix/router/console_formatter.ex
Compiled lib/phoenix/router/route.ex
Compiled lib/phoenix/router/scope.ex
Compiled lib/phoenix/supervisor.ex
Compiled lib/phoenix/socket/message.ex
Compiled lib/phoenix/router.ex
Compiled lib/phoenix/pubsub/local.ex
Compiled lib/phoenix/channel.ex
Compiled lib/phoenix/socket.ex
Compiled lib/phoenix/channel/server.ex
Compiled lib/phoenix/template/engine.ex
Compiled lib/phoenix/router/helpers.ex
Compiled lib/phoenix/template/exs_engine.ex
Compiled lib/phoenix/template/eex_engine.ex
Compiled lib/phoenix/template/html.ex
Compiled lib/phoenix/param.ex
Compiled lib/phoenix/socket/transport.ex
Compiled lib/phoenix/template.ex
Compiled lib/phoenix/token.ex
Compiled lib/phoenix/transports/serializer.ex
Compiled lib/phoenix/transports/long_poll_serializer.ex
Compiled lib/phoenix/transports/websocket_serializer.ex
Compiled lib/phoenix/transports/websocket.ex
Compiled lib/phoenix/transports/long_poll.ex
Compiled lib/phoenix/transports/long_poll_server.ex
Compiled lib/phoenix/test/channel_test.ex
Compiled lib/phoenix/controller.ex
Compiled lib/phoenix/view.ex
Compiled lib/phoenix/controller/logger.ex
Compiled lib/phoenix/endpoint/render_errors.ex
Compiled lib/phoenix/test/conn_test.ex
Generated phoenix app
==> phoenix_live_reload
Compiled lib/phoenix_live_reload/socket.ex
Compiled lib/phoenix_live_reload/channel.ex
Compiled lib/phoenix_live_reload/live_reloader.ex
Generated phoenix_live_reload app
==> postgrex
Compiled lib/postgrex.ex
Compiled lib/postgrex/binary_utils.ex
Compiled lib/postgrex/extension.ex
Compiled lib/postgrex/error_code.ex
Compiled lib/postgrex/error.ex
Compiled lib/postgrex/type_info.ex
Compiled lib/postgrex/extensions/text.ex
Compiled lib/postgrex/extensions/json.ex
Compiled lib/postgrex/result.ex
Compiled lib/postgrex/utils.ex
Compiled lib/postgrex/builtins.ex
Compiled lib/postgrex/type_server.ex
Compiled lib/postgrex/types.ex
Compiled lib/postgrex/messages.ex
Compiled lib/postgrex/connection.ex
Compiled lib/postgrex/extensions/binary.ex
Compiled lib/postgrex/protocol.ex
Generated postgrex app
==> ecto
Compiled lib/ecto/adapter/transaction.ex
Compiled lib/ecto/adapter/migration.ex
Compiled lib/ecto/adapter/storage.ex
Compiled lib/ecto/adapters/mysql/connection.ex
Compiled lib/ecto/adapters/connection.ex
Compiled lib/ecto/application.ex
Compiled lib/ecto/adapter.ex
Compiled lib/ecto/adapters/postgres/datetime.ex
Compiled lib/ecto/adapters/sql/query.ex
Compiled lib/ecto/data_type.ex
Compiled lib/ecto/migration/supervisor.ex
Compiled lib/ecto/model.ex
Compiled lib/ecto/model/optimistic_lock.ex
Compiled lib/ecto/migration.ex
Compiled lib/ecto/model/callbacks.ex
Compiled lib/ecto/migrator.ex
Compiled lib/ecto/migration/runner.ex
Compiled lib/ecto/pools/sojourn_broker/codel.ex
Compiled lib/ecto/pool.ex
Compiled lib/ecto/pools/sojourn_broker/timeout.ex
Compiled lib/ecto/pools/sojourn_broker.ex
Compiled lib/ecto/pools/poolboy.ex
Compiled lib/ecto/poison.ex
Compiled lib/ecto/pools/poolboy/worker.ex
Compiled lib/ecto/query/api.ex
Compiled lib/ecto/query/builder/distinct.ex
Compiled lib/ecto/query/builder/group_by.ex
Compiled lib/ecto/query/builder/from.ex
Compiled lib/ecto/pools/sojourn_broker/worker.ex
Compiled lib/ecto/query/builder/filter.ex
Compiled lib/ecto/query/builder/lock.ex
Compiled lib/ecto/query/builder/limit_offset.ex
Compiled lib/ecto/query/builder/join.ex
Compiled lib/ecto/query/builder/select.ex
Compiled lib/ecto/query.ex
Compiled lib/ecto/log_entry.ex
Compiled lib/ecto/adapters/sql/sandbox.ex
Compiled lib/ecto/query/builder/order_by.ex
Compiled lib/ecto/adapters/sql.ex
Compiled lib/ecto/query/builder/preload.ex
Compiled lib/ecto/query/builder/update.ex
Compiled lib/ecto/exceptions.ex
Compiled lib/ecto.ex
Compiled lib/ecto/adapters/postgres.ex
Compiled lib/ecto/changeset/relation.ex
Compiled lib/ecto/query/builder.ex
Compiled lib/ecto/adapters/postgres/connection.ex
Compiled lib/ecto/query/inspect.ex
Compiled lib/ecto/adapters/mysql.ex
Compiled lib/ecto/embedded.ex
Compiled lib/ecto/repo/assoc.ex
Compiled lib/ecto/repo.ex
Compiled lib/ecto/repo/supervisor.ex
Compiled lib/ecto/storage.ex
Compiled lib/ecto/queryable.ex
Compiled lib/ecto/repo/preloader.ex
Compiled lib/mix/ecto.ex
Compiled lib/mix/tasks/ecto.rollback.ex
Compiled lib/mix/tasks/ecto.migrate.ex
Compiled lib/ecto/query/planner.ex
Compiled lib/mix/tasks/ecto.gen.migration.ex
Compiled lib/mix/tasks/ecto.create.ex
Compiled lib/mix/tasks/ecto.gen.repo.ex
Compiled lib/mix/tasks/ecto.drop.ex
Compiled lib/ecto/repo/schema.ex
Compiled lib/ecto/type.ex
Compiled lib/ecto/repo/queryable.ex
Compiled lib/ecto/schema.ex
Compiled lib/ecto/uuid.ex
Compiled lib/ecto/association.ex
Compiled lib/ecto/changeset.ex
Compiled lib/ecto/migration/schema_migration.ex
Compiled lib/ecto/date_time.ex
Generated ecto app
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/json.ex
Compiled lib/phoenix_ecto/plug.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
==> phoenix_trello
Compiled lib/phoenix_trello/permalink.ex
Compiled lib/phoenix_trello.ex
Compiled web/channels/user_socket.ex
Compiled lib/phoenix_trello/board_channel/monitor.ex
Compiled web/helpers/session.ex
Compiled web/web.ex
Compiled lib/phoenix_trello/repo.ex
Compiled web/models/user_board.ex
Compiled lib/phoenix_trello/guardian_serializer.ex
Compiled web/models/comment.ex
Compiled web/models/list.ex
Compiled web/models/user.ex
Compiled web/models/board.ex
Compiled web/channels/board_channel.ex
Compiled web/models/card.ex
Compiled web/views/card_view.ex
Compiled web/controllers/page_controller.ex
Compiled web/controllers/api/v1/registration_controller.ex
Compiled web/controllers/api/v1/current_user_controller.ex
Compiled web/controllers/api/v1/card_controller.ex
Compiled web/controllers/api/v1/session_controller.ex
Compiled web/controllers/api/v1/board_controller.ex
Compiled web/views/board_view.ex
Compiled web/router.ex
Compiled web/views/current_user_view.ex
Compiled web/views/error_view.ex
Compiled web/views/session_view.ex
Compiled web/views/page_view.ex
Compiled web/views/registration_view.ex
Compiled web/views/layout_view.ex
Compiled lib/phoenix_trello/endpoint.ex
Generated phoenix_trello app
Consolidated Ecto.DataType
Consolidated Poison.Decoder
Consolidated Plug.Exception
Consolidated Phoenix.HTML.FormData
Consolidated Ecto.Queryable
Consolidated Poison.Encoder
Consolidated Phoenix.HTML.Safe
Consolidated JOSE.Poison.OrdEncoder
Consolidated Phoenix.Param
Consolidated List.Chars
Consolidated String.Chars
Consolidated Enumerable
Consolidated Collectable
Consolidated IEx.Info
Consolidated Inspect
[info] Running PhoenixTrello.Endpoint with Cowboy using http on port 4000
Hash: 8dc3aedd86d68cac6832
Version: webpack 1.12.11
Time: 3502ms
              Asset     Size  Chunks             Chunk Names
  js/application.js   1.7 MB       0  [emitted]  application
css/application.css  28.4 kB       0  [emitted]  application
   [0] multi application 40 bytes {0} [built]
    + 496 hidden modules

ERROR in ./web/static/js/phoenix.js
Module build failed: TypeError: /Users/jmd/code/oss/phoenix-trello/web/static/js/phoenix.js: Cannot set property 'Symbol(should not be considered a local binding)' of undefined
    at Object.push (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-helper-define-map/lib/index.js:96:37)
    at pushToMap (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:191:25)
    at pushMethod (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:531:10)
    at pushBody (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:312:16)
    at buildBody (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:244:10)
    at run (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:151:10)
    at PluginPass.ClassExpression (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:63:60)
    at newFn (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitQueue (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:159:21)
    at TraversalContext.visitMultiple (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/jmd/code/oss/phoenix-trello/node_modules/babel-traverse/lib/context.js:197:19)
 @ ./web/static/js/actions/sessions.js 13:15-36
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

Using:

npm 3.5.3
node 5.4.1
webpack 1.12.11
elixir 1.2.1

**Comment by johnmcdowall** [comment]
Seems that this could be a bug in the latest Babel, introduced with this change: https://github.com/babel/babel/commit/95c93dd22b7d2475a7bc4f90554c96e7bd2ad204#diff-e74a811eb852207068ca62abe7aa6638

Recommend pinning `babel-core` to 6.3.13. 

I would raise a bug with Babel but I refuse to use this garbage they're using for an issue tracker.
